language: node_js
node_js:
  - "6"
before_install:
  - sudo apt-get -qq update
  - sudo apt-get install -y libcairo2-dev libjpeg-dev libpango1.0-dev libgif-dev build-essential g++
  - cp config.json.example config.json
  - npm install -g mocha
